figure(); clf;

errorbar([stack_c.T_ign],...
    [stack_c.dim_c],...
    [stack_c.dim_c]-[stack_c.low_c],...
    [stack_c.high_c]-[stack_c.dim_c],...
    'ro');
hold on;

errorbar([stack_s.T_ign],...
    [stack_s.dim_c],...
    [stack_s.dim_c]-[stack_s.low_c],...
    [stack_s.high_c]-[stack_s.dim_c],...
    'bs');

plot(caroline_thesis_T_ign,...
    caroline_thesis_d_c,...
    'color',...
    get_rainbow_colour(3,4));

plot(caroline_thesis_T_ign,...
    caroline_thesis_t_c,...
    'color',...
    get_rainbow_colour(4,4));