% Plotting for varying L
xlabel ('\itL','FontSize',24);
ylabel ('\it\beta','FontSize', 24);
legend({'L = 10',...
    'L = 20',...}
    'L = 40',...
    'L = 80',...
    'L = 120',...
    'L = 160',...
    'L = 200',...
    'L = 240',...
    'L = 320'});

% for lx
% for i = 1:3
%     lx = log(all_data(i).t);
%     ly = log(all_data(i).W);
%     cftool(lx,ly);
% end