%% Formatting machinery

axis(axis_vector);
xlabel_handle = xlabel(xlabel_text);
set(xlabel_handle, 'FontName', font,...
                   'FontSize', font_size_L,...
                   'FontAngle', 'italic');
ylabel_handle = ylabel(ylabel_text);
set(ylabel_handle, 'FontName', font,...
                   'FontSize', font_size_L,...
                   'FontAngle', 'italic');

if ~isempty(legend_labels)
    legend(labels, 'Location', 'Best');
end

set(gca,'XMinorTick', 'on',...
        'YMinorTick', 'on',...
        'FontName', font,...
        'FontSize', font_size_S);
        %'XTick', x_tick_vector,...
        %'YTick', y_tick_vector);
    
box on;

% Set renderer options
set(1, 'Renderer', 'painters',...
       'RendererMode', 'manual');
