% import to solution
% grid isotherm
X_length = 50;
Y_length = 50;
tr = 1;
t = 30; % Snapshot at one instance of time
Z = zeros(X_length, Y_length);
for i = 1:X_length
    for j = 1:Y_length
        for p = 1:size(solution,1)
            if t > solution(p,4)
                Z(i,j) = Z(i,j) + ...
                    T_i_tr_boss(t-solution(p,4), ...
                        (solution(p,2)-i)^2 + (solution(p,3)-j)^2, ...
                        tr, lookup, dq, q_max) + ...
                    T_i_tr_boss(t-solution(p,4), ...
                        (solution(p,2)-i)^2 + (solution(p,3)+Y_length-j)^2, ...
                        tr, lookup, dq, q_max) + ...
                    T_i_tr_boss(t-solution(p,4), ...
                        (solution(p,2)-i)^2 + (solution(p,3)-Y_length-j)^2, ...
                        tr, lookup, dq, q_max);
            else
                break
            end
        end
    end
end
        