% Generates speed deficit plots -- for slab case.
% Data loaded: speed-deficit-summary

slab{1} = all_entries_slab_avg(93:129);
slab{2} = all_entries_slab_avg(130:177);

tau_c_vector = [1 10];
%%
figure(2);clf;
clear speed_plot;

%% Sketch
for i = 1:2
    tau = tau_c_vector(i);
    xx = 0.5 ./ ([slab{i}.Z] ./ sqrt(tau));
    yy = [slab{i}.speed_avg] .* sqrt(tau);
    speed_plot(i) = plot(xx([slab{i}.propagation_probability] > 0), ...
        yy([slab{i}.propagation_probability] > 0), 'o', ...
        'MarkerEdgeColor', colour_palette(i));
    if i == 1
        hold on;
    end
    plot(xx([slab{i}.propagation_probability] <= 0), ...
        zeros(size(yy([slab{i}.propagation_probability] <= 0))), 'x', ...
        'MarkerEdgeColor', colour_palette(i));
end

%% Continuum
speed_plot(i+1) = plot(slabContinuumX(slabContinuumY > 0), ...
    slabContinuumY(slabContinuumY > 0), 'o', ...
    'MarkerFaceColor', [1 0 0], ...
    'MarkerEdgeColor', [0 0 0]);
plot(slabContinuumX(slabContinuumY <= 0), ...
    slabContinuumY(slabContinuumY <= 0), 'x', ...
    'MarkerFaceColor', [1 0 0], ...
    'MarkerEdgeColor', [0 0 0]);

%% Labeling
set(gcf,'Position', [495   259   880   640]);
set(gca,'FontSize', 16)
xlabel('$1/2t$','interpreter', 'latex','fontsize', 24)
ylabel('$u$','interpreter', 'latex','fontsize', 24)
legend(speed_plot, {'$\tau_\mathrm{c} = 1$', ...
'$\tau_\mathrm{c} = 10$', ...
'Continuum'} ...
,'interpreter', 'latex', ...
'fontsize', 18 ...
);

set(gca,'TickLabelInterpreter','latex','TickLength', ...
    1.5*[0.01, 0.25], 'LineWidth', 1.2)