% Generates speed deficit plots -- for cylindrical case.
% Data loaded: speed-deficit-summary

%% Manual splitting
cyl{1} = all_entries_cyl_avg(130:180);
cyl{2} = all_entries_cyl_avg(181:240);
cyl{3} = all_entries_cyl_avg(241:246);
cyl{4} = all_entries_cyl_avg(247:260);

tau_c_vector = [1 10 30 50];
%%
figure(1);clf;

%% Sketch
for i = 1:4
    tau = tau_c_vector(i);
    xx = 1 ./ ([cyl{i}.Z] ./ sqrt(tau));
    yy = [cyl{i}.speed_avg] .* sqrt(tau);
    speed_plot(i) = plot(xx([cyl{i}.propagation_probability] > 0), ...
        yy([cyl{i}.propagation_probability] > 0), 'o', ...
        'MarkerEdgeColor', colour_palette(i));
    if i == 1
        hold on;
    end
    plot(xx([cyl{i}.propagation_probability] <= 0), ...
        zeros(size(yy([cyl{i}.propagation_probability] <= 0))), 'x', ...
        'MarkerEdgeColor', colour_palette(i));
end

%% Continuum
speed_plot(i+1) = plot(cylContinuumX(cylContinuumY > 0), ...
    cylContinuumY(cylContinuumY > 0), 'o', ...
    'MarkerFaceColor', [1 0 0], ...
    'MarkerEdgeColor', [0 0 0]);
plot(cylContinuumX(cylContinuumY <= 0), ...
    cylContinuumY(cylContinuumY <= 0), 'x', ...
    'MarkerFaceColor', [1 0 0], ...
    'MarkerEdgeColor', [0 0 0]);

% plot(slabContinuumX, slabContinuumY);

%% Labeling
set(gcf,'Position', [495   259   880   640]);
set(gca,'FontSize', 16)
xlabel('$1/d$','interpreter', 'latex','fontsize', 24)
ylabel('$u$','interpreter', 'latex','fontsize', 24)
legend(speed_plot, {'$\tau_\mathrm{c} = 1$', ...
'$\tau_\mathrm{c} = 10$', ...
'$\tau_\mathrm{c} = 30$', ...
'$\tau_\mathrm{c} = 50$', ...
'Continuum'} ...
,'interpreter', 'latex', ...
'fontsize', 18 ...
);

set(gca,'TickLabelInterpreter','latex','TickLength', ...
    1.5*[0.01, 0.25], 'LineWidth', 1.2)